# Generated by Django 4.0.5 on 2022-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='sex',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
