# Generated by Django 4.0.5 on 2022-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0002_wedding_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
