# Generated by Django 4.0.5 on 2022-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0003_wedding_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
