# Generated by Django 4.0.5 on 2022-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0004_alter_wedding_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='country',
            field=models.CharField(choices=[('FR', 'France'), ('USA', 'USA'), ('BLR', 'Belarus'), ('SPN', 'Spain'), ('ITL', 'Italy')], default='IRL', max_length=3),
        ),
    ]
