# Generated by Django 4.0.5 on 2022-06-19 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0005_wedding_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='country',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='sex',
        ),
        migrations.AddField(
            model_name='wedding',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='years',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
