# Generated by Django 4.0.5 on 2022-06-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0006_remove_wedding_country_remove_wedding_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='years',
            new_name='age',
        ),
    ]
