# Generated by Django 4.0.5 on 2022-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0013_alter_wedding_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='country',
        ),
    ]
