# Generated by Django 4.0.5 on 2022-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0018_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
