# Generated by Django 4.0.5 on 2022-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0025_alter_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
