# Generated by Django 4.0.5 on 2022-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0026_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(blank='', null=True),
        ),
    ]
