# Generated by Django 4.0.5 on 2022-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0028_alter_reservation_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(blank=True, default=None),
        ),
    ]
