# Generated by Django 4.0.5 on 2022-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0033_alter_reservation_add_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='add_person',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
