# Generated by Django 4.0.5 on 2022-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0034_alter_reservation_add_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='add_person',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
